spring:
  datasource:
    url: jdbc:h2:file:./devdb
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
logging:
  level:
    org.springframework: DEBUG
