spring: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
logging:
  level:
    org.springframework: DEBUG
